### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by rubberduck203** [gsscoder/CSharpx#1]
Am I missing something, or is there no license for this repository?
Did you intend to reserve all rights?

**Comment by gsscoder** [comment]
Sorry for replying so late,
project was created mainly for personal use that time... In latest weeks after years I'm back to work on it.

The lincense is now [MIT](https://github.com/gsscoder/CSharpx/blob/master/LICENSE).

**Comment by rubberduck203** [comment]
Awesome! Thanks!
